# A collaborative filtering-based approach to biomedical knowledge discovery

## Introduction

A scientist relies on knowledge contained in many published articles when developing a new hypothesis. Generating new hypotheses automatically based on extracting knowledge from academic publications is the problem faced by literature-based discovery (LBD) algorithms. These approaches are becoming more important as knowledge is spread out across larger number of publications. Text mining tools, including LBD methods, will likely become an essential tool to biology researchers as they explore new research ideas in their specific domains ([@ananiadou2006text]). Most approaches to LBD predict associations between two biomedical concepts that are not frequently discussed in the literature but are predicted to be strongly associated in the future.

Research in the LBD field was first prompted by Swanson's discussions of undiscovered knowledge and his associations of dietary fish oil and Raynaud's disease ([@swanson1986fish]). This early technique proposed the concept of open discovery in which a starting term (A) is selected and novel target terms (C) are predicted that are likely associated with A. Swanson's method proposed using intermediate terms (B) that are associated with A and C. For instance, dietary fish oil is mentioned in articles with blood viscosity and vascular reactivity. These two terms are also mentioned with Raynaud's disease. Swanson proposes that it is reasonable that dietary fish oil and Raynaud's disease may be associated, possibly as a treatment. This result has been validated experimentally ([@digiacomo1989fish]). [@hersh2008information] offers an overview of the different steps involved in the literature-based knowledge discovery problem.

Various tools have been developed to pursue this idea of predicting associations between previously unlinked biomedical terms. All these methods generate a score for a potential association which allow potential associations to be ranked. Swanson's Arrowsmith tool used cooccurrence of biomedical terms in titles from MEDLINE abstracts to identify known associations ([@swanson1997interactive]). The system required the user to input a starting term, gave them choices on the appropriate intermediate terms and ranked the predicted target terms based on the number of intermediate terms. Cooccurrences have proven a valuable metric for gauging concept associations and have been used in several systems including CoPub ([@frijters2008copub]). Many other systems have been developed using this concept with different methods for ranking the predictions and most systems generally use the text from the abstract, not just the title. Notable systems include FACTA+ that uses the probability of two terms appearing together in a publication given the frequency of the individual terms ([@tsuruoka2011discovering]). The BITOLA system uses the number of intermediate terms as well as the number of papers that support these intermediate links ([@hristovski2013using]). The ANNI approach uses a comparison of concept vectors to predict novel associations ([@jelier2008anni]). These concept vectors, based on the symmetric uncertainty coefficient ([@william2007numerical]), give a summary of the known associations of each concept with every other concept. The recent Implicitome project makes use of the same methodology as ANNI and has been integrated into the knowledge.bio project ([@hettne2016implicitome,bruskiewich2016knowledge]). These methods largely make use of local knowledge, which we define as knowledge of the intermediate terms that cooccur with the starting term and the target terms.

A thorough evaluation procedure has previously been proposed to evaluate the different scoring methods ([@yetisgen2009new]). It uses publications before a certain year as the input to each approach and evaluates their scoring of novel associations in newer publications. The authors also propose using precision-recall curves as a metric for success which is supported by analysis of the similar link prediction problem ([@lichtnwalter2012link]).

Recommendation systems are used in many commercial products such as Amazon and Netflix to suggest relevant products to a customer given their previous purchasing or viewing history. These systems often rely on collaborative filtering algorithms which use the combined history of many users and products. The success of these approaches are largely down to their use of global knowledge whereby they can implicitly learn about types of users or products based on this combined history and not on any individual user, product or user-product interactions. The Netflix Prize spurred development of new recommendation algorithms and many of the most successful techniques were based on matrix decomposition ([@bennett2007netflix]). We propose that similar techniques should be used for literature-based discovery. Instead of associations between users and products, these techniques could be reformulated to predict associations between biomedical terms. They would therefore be able to use global knowledge about the cooccurrence patterns of all entities and be able to implicitly learn about different types of entities. Latent semantic indexing (LSI), a matrix-based approach for finding term similarity, has previously been examined for recapitulating Swanson's fish oil discovery but was limited by computational cost ([@gordon1998using]) .

The literature-based discovery problem can be thought of as a implicit feedback problem (also known as one-class collaborative filtering ([@pan2008one])). Implicit feedback problems, such as user purchase history, have only positive data points. Missing data may be negative or real missing data. In LBD, we have known associations between biomedical concepts, as they are discussed in the same publications. However two terms that have never appeared together before can mean two different things: either this is an association that has not yet been discovered, or the two concepts are definitely not associated.


In this paper, we present the singular value decomposition (SVD) method as the best method for predicting associations between biomedical concepts. We use a similar approach in creating a gold standard data set to the previous comprehensive comparison of knowledge discovery methods ([@yetisgen2009new]). We build up a training set of cooccurrences extracted from PubMed abstracts and PubMedCentral full-text articles up to the year 2010. We then compare methods using their predictions on novel cooccurrences that appear in literature after the year 2010. We also explore the predictive power of this approach to discover associations that appear in literature at various time-points after 2010. Finally, we delve into the several specific associations to examine the strengths and limitations of our SVD method compared to the commonly cited Arrowsmith method.

## Materials and Methods

In order to evaluate different knowledge discovery systems, we extract a set of cooccurrence relationships to use as training and test sets. These cooccurrences are between different biomedical concepts extracted from the Unified Medical Language System (UMLS) within the same sentence.

### Word List

A list of controlled vocabulary terms with synonyms was generated using the UMLS Metathesaurus (version 2016AB - Active Set). The terms selected were filtered from the Semantic Medline groups Anatomy (ANAT), Chemicals and Drugs (CHEM), Disorders and diseases (DISO), Genetics (GENE) and Physiology (PHYS) ([@kilicoglu2008semantic]). The Findings group (T033) was removed due to a large number of vague terms. This generated a list of 1,345,346 terms which was filtered using a set of stop words combined from the NLTK toolkit ([@bird2006nltk]) and the most frequent 5,000 words based on the Corpus of Contemporary American English ([@davies2009385]). Notably, only ~26% of the terms were found to appear within the downloaded article and abstract text.

All terms in the UMLS Metathesaurus are associated with multiple synonyms and contain alternative spellings and other wordings for the same term. All synonyms were used and matched to a single term ID in the generated word list. When a word (or multiple words) was found in a sentence which was associated with multiple concepts, the cooccurrences were counted for all possible concepts.

### Positive Data

Cooccurrence relationships were extracted from biomedical literature to identify potential associations between biomedical terms. Raw text was extracted from titles and abstracts from MEDLINE citations and the titles, abstracts and full texts from PMC Open Access Subset articles. Many relationships may be mentioned in the full paper but not in the abstract as shown in ([@van2013large]). Therefore, full articles where available, as well as abstracts, were used to identify the largest number of relationships. In total, 13,153,418 abstracts and 1,503,065 full articles were downloaded from MEDLINE and PubMed Central (downloaded through FTP on 12th Feb 2017). In order to avoid duplication, articles that appear in PMC were filtered out of the MEDLINE data set.

These texts were filtered to remove HTML tags and Unicode special characters. They were split into sentences using LingPipe v4.1.0 (downloaded from http://alias-i.com/lingpipe) and tokenized using the GENIA part-of-speech tagger v3.0.1 ([@tsuruoka2005developing]). Exact string matching was used to identify entities from the UMLS-based word list. Longer terms were extracted first and removed from the sentence. This meant that a sentence discussing "tumor necrosis factor" would be flagged for "tumor necrosis factor" and not for "tumor necrosis". The tokenization was used to identify word boundaries, such that "non-cancerous tumor" was not flagged as "cancerous tumor". When multiple terms appear in a sentence, all pair-wise cooccurrences were recorded.

### Sampling and Negative Data

Ideally to evaluate a scoring method, we would calculate the scores for all possible novel cooccurrences, which are defined as cooccurrences that do not appear in the training set. We would then evaluate the difference in scores for known novel cooccurrences in the test set compared with negative cooccurrences, which are those that do not occur in the test set. It is important to note that while all LBD methods discussed in this paper use only positive data (cooccurrences that do occur in literature) to calculate scores, our evaluation methodology will require the generation of negative data (cooccurrences that neither appear in training or test data).

The training set, from publications published up to and including the year 2010, contains 101,139,316 cooccurrences between 305,077 unique biomedical concepts. The size of the set of cooccurrences that could be predicted as novel is ~46.4 billion. The test set contains 65,680,905 novel cooccurrences observed in publications published after the year 2010 and therefore makes up only 0.14% of possible novel cooccurrences.

It is computationally infeasible to evaluate the full space of possible cooccurrences so instead a large sampling approach is taken. 1,000,000 random cooccurrences are selected from the test set that represent known novel associations (also referenced as positive cooccurrences). To match the 1,000,000 positive cooccurrences, the same number of "negative" cooccurrences are randomly generated. These are cooccurrences that don't appear in the training or test data and are very likely not real associations.

### SVD Method

The SVD approach treats the cooccurrence data as a binary adjacency matrix $ X $ where $ X_{ij] $ is $ 1 $ if the terms $ i $ and $ j $ have appeared in a sentence together and $ 0 $ if they have not. The matrix is square, symmetric, generally very sparse and has the dimension of the number of terms in the vocabulary. A complete SVD decomposes it into three matrices such that $ X = U \Sigma V^T $ where $ X $ is the adjacency matrix, $ U $ and $ V $ contain the singular vectors and $ \Sigma $ is a diagonal matrix containing the singular values.

We use a truncated form of SVD in which we only use a small number of the singular values in order to create a low-rank approximation of the matrix. In this case, we decompose $ X \approx U_{k] \Sigma_{k] (V_{k])^T $ in which we keep the first $ k $ singular values and vectors. This means that each term $ i $ has a dense representation as the $ i $th truncated singular vectors in $ U_{k] $ and $ V_{k] $.

By reducing the dimensionality, this approach is able to summarize the original matrix ([@eckart1936approximation]). We used the Graphlab implementation v2.2 ([@low2014graphlab]) (built from Dato Powergraph Github repository at https://github.com/dato-code/PowerGraph) which uses the Lanczos algorithm. When the truncated SVD is used to reconstruct the matrix, every possible cooccurrence is given a real-valued score which we designate the SVD score. The SVD method gives cooccurrences that are predicted to not appear in future literature a score close to zero, and those that will appear a score closer to one.

There is only one parameter for the SVD method which is the number of singular values $ k $ to use for reconstructing the matrix. In order to choose the value for this, we take a cross-validation approach in which we use a further time-split data set. Publications up to the year 2009 are used to generate a cooccurrence training set. And then 1,000,000 novel cooccurrences are randomly sampled from publications in the year 2010. The same negative data generation and sampling approaches are used and precision-recall curves are generated for each rank parameter. By selecting the parameter that gave the largest area under the precision-recall curve, 132 was chosen as the number of singular values. 

The SVD method provides scores with a range of approximately zero to one. By setting a different threshold on these scores in order to select the set of predictions, a trade-off of precision and recall can be made. With $ k = 132 $, the associated precision-recall curve is examined to identify the optimal trade-off which is equivalent to maximizing the F1-score.  We find the score threshold that gives the largest F1-score is 0.44.

### Evaluation

TABLE HERE

Based on previous literature we selected 8 other knowledge discovery algorithms for benchmarking. These methods are based on the number of cooccurrences of terms and occurrences of individual terms. Table~\ref{tab:equations] gives an overview of the equations implemented for the scoring methods. $ score(x,y) $ is the score calculated between term $x$ and $ z $. $ c_i $ is the set of terms that cooccur with term $ i $. $ v_i $ is the concept profile vector as defined in [@jelier2008literature]. FACTA+ requires knowledge of the set of sentences that contain term $ i $ which is defined as $ s_i $. The SVD method uses truncated versions of the decomposed matrices $ U $, $ \Sigma $ and $ V $. $ U_{k] $ is the truncated $ U $ matrix with only the first $ k $ columns kept. $ (U_{k])_x $ is the $ith$ row of the $ U_{k] $ truncated matrix from the SVD decomposition. The same terminology is used for the $ \Sigma $ and $ V $ matrices.

The Arrowsmith algorithm counts the number of intermediate terms also known as the linked term count (LTC). The average minimum weight (AMW) method calculates the path with minimum support between two concepts. An amalgamation of LTC-AMW, in which LTC is used to rank first and then AMW is used as a secondary ranking criterion, was identified as the top performing methods in a previous comparison of literature-based discovery ([@yetisgen2009new]). We implement LTC-AMW by simply scaling the LTC score up so that the smallest LTC score is larger than the largest AMW score and then add the AMW score and order accordingly. We also compare two successful methods from the link prediction literature, the Jaccard Index and Preferential Attachment ([@liben2007link]). Finally we compare three methods from more recent literature-based discovery methods: ANNI, BITOLA and the FACTA+ reliability measure. 

Precision-recall curves were chosen as the evaluation procedure due to the large class imbalance. Previous analysis has shown that receiver operating characteristic (ROC) curves are not appropriate for problems with large class imbalance ([@lichtnwalter2012link]). When calculating the precision, the prior known class balance , based on the training set, is taken into account. While our test data of positive and negative sampled cooccurrences shows a 50% class balance, the real training data shows a class balance, $ b $, of approximately 0.14% positive cooccurrences within all possible cooccurrences. This information is used to reweight the precision calculation as below where $ TP $ is the count of true positives and $ FP $ is the counter of false positives.

$ precision = \frac{b \times TP]{b \times TP + (1-b) \times FP] $

Recall is calculated as normal and does not require any correction. The F1-score is calculated using the normal recall and the corrected precision.



## Results]

### Methods comparison]


FIGURE HERE


The 9 methods were compared on the same data set of 2,000,000 randomly sampled positive and negative cooccurrences. In order to visualize the different scoring methods more intuitively, we show violin plots of the various scores for the positive and negative sets in Figure~\ref{fig:scores]. The perfect knowledge discovery algorithm would display two separable distributions for the positive and negative sets. However, none of distribution pairs are easily separable showing that none of the algorithms are capable of completely differentiating positive and negative cooccurrences. The performance metrics for the runs of the algorithms are included in the Supplementary Materials.


FIGURES HERE

In order to quantitatively compare the different sets of scores, we used the area under the corresponding precision-recall curves which are shown in Figure~\ref{fig:comparison]. Notably, SVD outperforms all the other methods. This suggests that the SVD approach, which is a form of dimensionality reduction, is able to compress the knowledge into a reduced form and generalize the knowledge of the matrix. The associated precision-recall curves, shown in Figure~\ref{fig:prcurves] highlight that SVD can gain surprisingly high precision if a low recall is acceptable to the user. Arrowsmith gives the second best performance showing that the simple count of intermediate terms gives a strong measure of association between two terms.

While Figure~\ref{fig:scores] suggests that FACTA+ does have different distributions for the positive and negative cooccurrences, the performance shown in Figure~\ref{fig:comparison] is surprisingly low. Further analysis showed FACTA+ predicts associations between many extremely rare terms with high probability, a result that disagrees with all other scoring methods. For example, the terms "discorhabdin Y" and "aspernidine A" are predicted to be associated with a probability of 1.0. However both of them only appear in a single sentence each. Given the extreme rarity of these terms, this is a very weak association and likely not helpful. They share a single intermediate term: "alkaloids" that appears in 32,749 sentences, including the single sentences that contain the rare terms. The high probability score is due to the max function used to combine the conditional probabilities $ P(V|W) $ and $ P(W|V) $ to calculate $ D(V,W) $. The conditional probability $P(V|W)$ represents the probability of one term $V$ appearing in a sentence that also contains term $W$. Given a common term $ V $ (e.g. "alkaloids") that occurs in a high proportion of the sentences that a rare term $ W $ (e.g. "discorhabdin Y") appears, $P(V|W) $ will be very large and $ P(W|V) $ will be extremely small. The max value will always use $P(V|W)$ and these high values skew the results.

The previous comparison analysis ([@yetisgen2009new]) concluded that the LTC-AMW was the best knowledge discovery method. Our analysis shows the LTC-AMW performs similarly to the Arrowsmith which is equivalent to the linked term count (LTC). This suggests that the improvement of LTC-AMW over AMW previously shown is based entirely on the linked term count and that AMW doesn't contribute at all.

### Predictions over time]

FIGURE HERE

We also explored predictions for novel cooccurrences that appear in publications at different time points. We again used the data set of cooccurrences from papers up to and including the year 2010. We then found all novel discoveries after this period and grouped them by the year in which they first appear. There were on average 10.9 million novel cooccurrences in each year from 2011 to 2016 inclusive. Using the optimal parameters ( $ k = 132 $ ) for the SVD model, we then calculate the scores using 1 million randomly sampled cooccurrences from each year (for computational reasons). Using the previously selected threshold value of 0.44 on the scores to filter out predictions, we calculate the recall values for each year. These are presented in Figure~\ref{fig:yearbyyear].

The model is best able to predict cooccurrences in the year immediately after the data set ends (2011). The recall then decreases each year. This means that novel cooccurrences that appear further in the future are harder to predict. This result makes sense as a large proportion of next year's discoveries will be based closely on existing discoveries. This could be a new drug tested on a similar disease to the current use of the drug or a different member of a gene family being associated with the same disease. However, cooccurrences further into the future are based on more complicated interpretations of the current research or more likely, new research that has yet to be published.

Importantly, this model should not create too many predictions as to overwhelm a researcher and artificially inflate recall values. The SVD approach makes 12,242,242 cooccurrence predictions with a score above the required threshold. This number of predictions seems reasonable as it is smaller in magnitude to the known number of real novel cooccurrences (65,680,905) in the same time period. One further comment is that a number of the predictions that don't match with a novel discovery in the years up to 2016 will likely appear in future years after 2016.

### Comparison of predictions between SVD and Arrowsmith methods]

In order to explore the strengths and weaknesses of the SVD approach, we examine four results from the SVD system with comparisons to the output of the Arrowsmith system. The Arrowsmith system is used for comparison as it is the second best performing system. The associated UMLS Concept Unique Identifier (CUID) is noted for each term.

The first case examines the highest scoring prediction from the SVD from our test set. This is an association between "Obstruction" (C0028778) and "Structure of anulus fibrosus of intervertebral disc" (C0223087). SVD gives this association a score of 1.320. The Arrowsmith method also gives this a high score with 1804 intermediate terms. This prediction turns out to be correct and is found in 7 separate sentences in publications after 2010. One of the papers ([@kang2014interference]) discusses using a block (synonym of "Obstruction" term) to interfere with the "annulus fibrosus" as an experimental model. It is common to block or obstruct parts of the spine to understand developmental biology, hence it is understandable that both SVD and Arrowsmith would make this prediction.

The next case to examine is one in which the SVD method predicts an association which is missed by the Arrowsmith method. Here we find all associations with SVD score above the previously defined threshold of 0.44 and seek the association with lowest Arrowsmith score. This is the association of "Proteins" (C0033684) and "hydantoin racemase" (C0168561). This association has SVD score=0.464 and Arrowsmith score=55. The association is also correct as it is found in a publication during the test period. Hydantoin racemase is an enzyme encoded by a gene in several strains of bacteria. It is unsurprising that there would be discussion of the protein product of this gene and that this association would occur. The SVD method likely implicitly identifies that hydantoin racemase is an enzyme as the pattern of cooccurrences between the enzyme and other terms is similar to other enzymes. Other enzymes are commonly discussed with the word "proteins" as most enzymes are proteins. Arrowsmith likely fails to generate a high score because this is an infrequently discussed enzyme (only appearing in 37 sentences in our corpus and cooccurring with 57 other terms). This suggests that the SVD method may be more successful for infrequently discussed terms.

Next we examine a case where the SVD method failed to predict an association that Arrowsmith found. We look for a case where the Arrowsmith score is above the thresholds defined in Supplementary Table~3 but has the lowest SVD score. This association is between "Surgical Flaps" (C0038925) and "MAP2 gene" (C1417006). Note that "Surgical Flaps" also has the synonym "Flap" and "Flaps". Arrowsmith gives this a high score of 2327, but SVD gives a very low score of -0.175. This association is deemed correct as it appears as a positive association in the test set. However the article in which it appears ([@chu2013flap]) uses "FLAP" to refer to a particular protein and not the expected context of surgical flaps. This shows the limitation of using exact string matching to identify biomedical terms using the UMLS set of synonyms. The question remains why Arrowsmith gives a high score, but the SVD method provides a low score. One likely explanation is that the "Surgical Flaps" term cooccurs with a large number of terms (15,374) of which only 2,327 (~15%) cooccur with the "MAP2 gene" term. The Arrowsmith method only takes those ~15% into account whereas SVD takes into account the complete cooccurrence pattern when predicting associations. Most of these cooccurrences will be related to "flaps" and "surgical flaps" and not to gene/protein related terms.

Lastly we look at the association with the highest SVD score that was deemed a negative association within our test set, that is one that did not occur in any publications within our corpus. This association is between "Kidney Failure, Acute" (C0022660) and "Thalassemia" (C0039730). The SVD method gave this a score of 0.895 and the Arrowsmith also gave a very high score of 2987. Thalassemia is a group of disorders associated with low haemoglobin production. A publication in 2011 ([@quinn2011renal]) notes that "Little is known about the effects of thalassaemia on the kidney" and goes on to study the association of thalassemia with renal issues and finding strong links. This suggests that this association is a valid prediction and exemplifies the power of knowledge discovery methods to identify valid links between biomedical terms.

These examples have highlighted several strengths and weaknesses of the SVD and Arrowsmith approaches. Firstly Arrowsmith can be confused by very frequently appearing terms (such as the "Flap" term). It can miss infrequently mentioned terms (such as "Hydantoin racemase"). SVD is able to identify important characteristics of a term, even with infrequent mentions (as was the case for "Hydantoin racemase"). On the other hand, SVD can also be confused by terms that have a lot of synonyms. If one of the synonyms is a frequently occurring and ambigious term, the SVD method can put too much weight on cooccurrences from this synonym. This limitation may be improved with the development of a named entity recognition (NER) system that can distinguish the context for different UMLS terms. A method built upon the NER systems evaluated in [@funk2014large] would be an interesting direction for a future LBD system.

## Discussion

The success of singular value decomposition over the other current methods for knowledge discovery suggests that the matrix deconstruction approach may be the best avenue for further improvements in knowledge discovery. By compressing the cooccurrence information down to a dense representation of each concept (the row $ U_i $ of the $ U $ matrix that corresponds to term $ i $), SVD is able to deal with the sparsity inherent in the cooccurrence data. Furthermore it deals with two concepts that aren't frequently discussed together but share the same pattern of cooccurrences with other biomedical concepts. An example would be a drug with generic name and brand names as separate terms in the wordlist (e.g. erlotinib and Tarceva). It would be sensible to merge these entities, however, most knowledge discovery techniques would not be able to do this automatically. Because the two concepts share similar cooccurrence patterns, singular value decomposition will decompose them to similar dense representations and make use of both their cooccurrence patterns to predict new associations. From the recommendation systems perspective, this can be viewed as two customers that watch the same genres of movies but have never watched the exact same movie. The matrix decomposition method is able to identify that these customers share similar tastes and use each others' viewing history to make recommendations.

SVD does, however, have several drawbacks. The first is that it is still computationally expensive. Our SVD runs required ~16GB of memory and about 6 hours per run (on a machine with quad Intel E5-4640 processors). This could be ameliorated through trimming very rare terms, thereby reducing the size of the matrix for decomposition. Furthermore, this will become less of a problem as memory costs decrease. Another issue with singular value decomposition is interpretability so that a user can understand why a prediction is made. Classic methods, such as the Arrowsmith approach, allows the user to view the intermediate concepts that were used to generate the prediction. As there are no intermediate concepts in the SVD model, it is more challenging to display the rationale for prediction. One approach would be to show the concepts with similar dense representations in order to give context to the user of why these two concepts are predicted to cooccur and presents an interesting future direction for research.

There are many general terms in the UMLS word lists, such as "Local Anesthetic", which may not prove to be useful drug associations. One approach would be to attempt to filter these terms out of the word lists entirely. However, it could be argued that these terms are valuable in understanding the context of other concepts, and in creating their implicit relationships. Hence it would likely be more valuable to filter them out later in the process so that they are not shown as predictions but are used during the singular value decomposition.

The evaluation approach of making predictions using a training set and comparing predictions to a test set (as previously used by [@yetisgen2009new]) does have several limitations. The most important for a knowledge discovery algorithm is that many of the predictions deemed as false positives may prove to be true positives as new research is published. This limitation is hard to overcome. Knowledge base completion algorithms make use of a ranking evaluation where the ranking of randomly sampled known positive associations within the full set of predictions is calculated (as used in [@lin2015learning]). This is used to compare systems and avoids the problem of false positives but is also very challenging to interpret correctly. By using a training/test split approach, the associated metrics of recall and precision give a lower limit to the performance of each system which is easier to interpret. However a testing methodology that avoids the issue of negative data really being positive data (that will appear in future publications) but is also easy to interpret remains an open problem.

FIGURE HERE

While the SVD method clearly outperforms the other methods, an obvious question is whether the different systems make similar predictions. Figure~\ref{fig:predictionscomparison] examines the overlap of top performing systems. LTC-AMW and Arrowsmith give very similar predictions so only Arrowsmith is included. The method for deciding these set of predictions given the scores generated for each system is outlined in the Supplementary Materials. There are a core set of predictions that are shared by each method. However a large number of predictions are made by each system individually. This points towards the development of a meta-method that combines the different predictions of multiple systems and is an interesting direction for future work.

Finally, it is worthwhile to note that our decision to focus on sentence level cooccurrence, as opposed to abstract level cooccurrence, was based on reducing potential incorrect associations. These happen between terms that cooccur but do not have any real biological relationship. By increasing the amount of text within which a cooccurrence can happen (e.g. to a full abstract), there are likely many more incorrect associations. However to check that this decision didn't bias out results, we reran the entire analysis pipeline using abstract-level cooccurrences. In this case a cooccurrence occurs when two terms appear in the same abstract. The results (shown in the Supplementary Materials) show a similar pattern to the sentence-level results and that SVD is the best performing system for this type of cooccurrence.

## Conclusions

Our study has shown that the singular value decomposition technique provides the best scoring method for predicting future cooccurrences when compared to the leading methods in the knowledge discovery problem. The method is best able to predict cooccurrences that occur in publications in the near future and slowly reduces in predictive power for the far future. We hope this analysis will benefit the knowledge discovery research community in developing tools that will be beneficial for molecular biology researchers.