--- 
title: "Building and inferring knowledge using biomedical text mining"
author: "Jake Lever"
date: "June 2018"
site: bookdown::bookdown_site
output:
  bookdown::pdf_book
documentclass: ubcthesis
#classoption: graybox,envcountchap,sectrefs
#bibliography: [01-intro.bib,02-svd.bib,03-versekindred.bib]
bibliography: thesis.bib
biblio-style: apalike
link-citations: yes
github-repo: jakelever/thesis
description: "This is my PhD thesis on biomedical text mining"
---


```{r bibliographyMerge, eval=T, echo=F}
library(RefManageR)
BibOptions(check.entries=F)
bibfiles <- list.files(pattern = "\\.bib$")
bibfiles <- grep("thesis.bib",bibfiles,invert=T,value=T)
bib <- ReadBib(bibfiles[1])
for(bibfile in bibfiles[2:length(bibfiles)])
  bib <- suppressWarnings(suppressMessages(merge(bib,ReadBib(bibfile))))

suppressWarnings(suppressMessages(WriteBib(bib, file='thesis.bib',check=F)))
```

# List of Abbreviations {-}

```{r abbreviations, eval=T, echo=F}
library(kableExtra)
library(dplyr)
abbreviations <- read.table('data/abbreviations.tsv',sep='\t',comment='')

knitr::kable(abbreviations,
  booktabs = TRUE, escape=FALSE,
  col.names = c('Short','Long')
  )
```


# Acknowledgements {-}

Thanks everyone

# Dedication {-}

To Gromit (and Wallace)
